namespace PizzaBot.Orders
{
  internal enum Topping
  {
   PEPPERONI, SAUSAGE, BACON, CHICKEN, HAM, BEEF, STEAK, SALAMI, ONION, MUSHROOMS, 
   PEPPERS, PINEAPPLE, OLIVES, TOMATOES, SPINACH, JALAPENOS, PROVOLONE, CHEESE, CHEDDAR,
  }
}